### ISSUE TITLE
Dialog text padding

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [ACRA/acra#596]
![image](https://user-images.githubusercontent.com/7463564/29888856-86126366-8dc2-11e7-9059-f8095014949d.png)

How can I fix this padding?

I am using app compat theme, light dialog.

**Comment by F43nd1r** [comment]
Which padding do you want to fix?

**Comment by F43nd1r** [comment]
No feedback - closing.

**Comment by timautin** [comment]
Hello,
He meant the left and right padding, to respect Material Design guidelines. It would be nice if the default dialog respected it rather than using pre-Lollipop design ;)

**Comment by mikehardy** [comment]
@timautin open source means "It would be nice" should always read as "would you accept a PR that implemented...", then, the PR :-)

**Comment by timautin** [comment]
@mikehardy I know but a PR to add a 24dp padding line 108 of https://github.com/ACRA/acra/blob/master/acra-dialog/src/main/java/org/acra/dialog/CrashReportDialog.java seems a bit overkill ;) . Looks like there's no dp <-> px conversion method in the code, so here's one:

```
public static int dpToPx(Context context, int dp) {
    return (int) ( (float) dp * context.getResources().getDisplayMetrics().density);
}
```

**Comment by F43nd1r** [comment]
@timautin problem already solved in #782. Doing it correctly: Loading the value from the theme. Old hardcoded value can stay as a fallback.

**Comment by timautin** [comment]
@F43nd1r Great, that even better :) ! I was still using version 5.3 with a BaseCrashReportDialog subclass, I'm now migrating to 5.5. It still doesn't work by default, and I'm struggling to get the theme setup properly. Is there a wiki page with up to date information about this?

**Comment by F43nd1r** [comment]
Theme can be set in configuration, see https://www.acra.ch/javadoc/5.5.1/org/acra/annotation/AcraDialog.html#resTheme-- e.g. `@AcraDialog(resTheme = R.style.AppTheme_Dialog)`

But
- the PR is not merged into any release yet
- If you were using a BaseCrashReportDialog, you weren't using any of ACRAs layouts anyway.

**Comment by timautin** [comment]
Oh ok, seems I was doing it properly then (I was wondering why the padding wasn't taken into account). Seems the buttons style is ignored as well (the color is wrong and the have a grey background). I'm using this theme:

```
<style name="AlertDialogStyle" parent="Theme.MaterialComponents.Light.Dialog.Alert">
    <item name="android:textColorPrimary">@color/darkGrey</item>
    <item name="android:textColor">@color/black</item>
    <item name="colorAccent">@color/colorAccent</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="dialogPreferredPadding">24dp</item>
    <item name="android:buttonStyle">@style/DialogButtonsStyle</item>
</style>

<style name="DialogButtonsStyle">
    <item name="android:textColor">@color/colorAccent</item>
</style>
```

I'll stick with a custom dialog then, but I didn't find a wiki page about the migration from BaseCrashReportDialog to POJOs, is there any?

I know that I wasn't using ACRA's layouts, I was trying to remove my BaseCrashReportDialog subclass with the 5.5.1 migration.

**Comment by F43nd1r** [comment]
> Seems the buttons style is ignored as well (the color is wrong and the have a grey background).

This is working for me.
```xml
    <style name="AppTheme.Dialog" parent="Theme.AppCompat.Dialog">
        <item name="android:buttonStyle">@style/DialogButtonsStyle</item>
    </style>

    <style name="DialogButtonsStyle">
        <item name="android:textColor">@color/colorAccent</item>
    </style>
```



> I'll stick with a custom dialog then

Alternative quick fix: Extend CrashReportDialog and override

    @NonNull
    protected View buildCustomView(@Nullable Bundle savedInstanceState) {
        View v = super.buildCustomView(savedInstanceState);
        v.setPadding(your padding);
        return v;
    }

> but I didn't find a wiki page about the migration from BaseCrashReportDialog to POJOs, is there any?

Here's one: Use any activity as Superclass instead of `BaseCrashReportDialog`. At some point (recommended: in `onCreate`) create an instance of `CrashReportDialogHelper(this, getIntent())` and use its methods `sendCrash` and `cancelReports` in place of their equivalents in `BaseCrashReportDialog`

**Comment by timautin** [comment]
Thank you very much! For anyone reading this, I'm doing this:

```
public class CustomAcraReportDialog extends AppCompatActivity {

    CrashReportDialogHelper _helper;
    EditText _commentEditText;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);

        supportRequestWindowFeature(Window.FEATURE_NO_TITLE);

        _helper = new CrashReportDialogHelper(this, getIntent());

        MaterialAlertDialogBuilder builder = new MaterialAlertDialogBuilder(this);
        builder.setIcon(R.drawable.ic_bug_dark);
        builder.setTitle(R.string.crash_dialog_title);
        builder.setView(R.layout.dialog_custom_acra_report);
        builder.setPositiveButton(R.string.crash_send_button, (dialogInterface, i) -> { _helper.sendCrash(_commentEditText.getText().toString(), null); finish(); });
        builder.setNegativeButton(R.string.common_cancel, (dialogInterface, i) -> { _helper.cancelReports(); finish(); });
        builder.setOnCancelListener(dialogInterface -> { _helper.cancelReports(); finish(); });

        AlertDialog alert = builder.create();
        alert.setOnShowListener(dialog -> _commentEditText = alert.findViewById(R.id.user_comment));
        alert.setCanceledOnTouchOutside(false);
        alert.show();
    }
}
```

Here's the layout:

```
<?xml version="1.0" encoding="utf-8"?>
<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingLeft="24dp"
        android:paddingRight="24dp"
        android:paddingBottom="20dp"
        android:paddingTop="20dp"
        >

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="@string/crash_dialog_comment_prompt" />

        <EditText
            android:id="@+id/user_comment"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textMultiLine"
            android:layout_marginTop="10dp"
            android:hint="@string/crash_dialog_comment_hint" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:text="@string/crash_dialog_update_reminder" />

    </LinearLayout>

</ScrollView>
```

And the manifest declaration:

```
<activity
    android:name="com.at.ewalk.commons.ui.CustomAcraReportDialog"
    android:excludeFromRecents="true"
    android:finishOnTaskLaunch="true"
    android:launchMode="singleInstance"
    android:process=":acra"
    android:theme="@style/AppTheme.Dialog"/>
```

**Comment by F43nd1r** [comment]
ACRA 5.6.0 now has the PR merged. @timautin it would be nice if you could test if this suits your usecase, and if not open an issue about what's missing.
