### ISSUE TITLE
In Java code how replace reportSenderFactoryClasses with v5.8.1

### ISSUE THREAD

**Issue by draekko** [ACRA/acra#848]
**Required reading**
https://github.com/ACRA/acra/wiki/How-to-debug-ACRA

**Describe the bug**
Cannot find a way to replace reportSenderFactoryClasses in java code. The documentation doesn't list any replacement and half the site documentation link say they are 404 page not found. 

**Expected behavior**
Expecting a description or sample code for Java to be able to call a custom ReportSender. The link to the ReportSenderFactory says 404 and there is no example or code to connect it to the "plugin system".

**Version**
 - ACRA [5.8.1]

**Comment by F43nd1r** [comment]
http://www.acra.ch/docs/Senders#registering-your-sender link has been fixed.

**Comment by draekko** [comment]
Thanks for fixing the rest of the documentation BUT AutoService still doesn't work on a pure java project and its not clear how i can get the factory registered for a custom sender.

**Comment by draekko** [comment]
Opened a new issue #852 to leave this one closed.
